name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.0
  cached_network_image: ^2.3.3
  webview_flutter: ^1.0.5
  flutter_icons: ^1.1.0
  provider: ^4.3.2+2
  page_transition: ^1.1.7+2
  fluid_bottom_nav_bar: ^1.2.0
  intl: ^0.16.1
  jiffy: ^3.0.1
  flutter:
    sdk: flutter
  share: any
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/loading/load.gif
